Deploy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,9 +18,7 @@ jobs:
           cache: maven
 
       - name: Build app with Maven
-        run: |
-          mvn clean package -DskipTests=true
-
+        run: mvn package -DskipTests=true
 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
@@ -37,30 +35,32 @@ jobs:
           context: .
           file: ./Dockerfile
           push: true
-          tags: ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest
-            - name: Restart MySQL container
-              uses: appleboy/ssh-action@v1.0.3
-              with:
-                host: ${{ secrets.SSH_HOST }}
-                username: ${{ secrets.SSH_USERNAME }}
-                password: ${{ secrets.SSH_PASSWORD }}
-                script: |
-                  if ! docker network ls | grep -q "coffeestore-miahkykh"; then
-                  docker network create coffeestore-miahkykh
-                  fi
-                  echo "Restarting MySQL container"
-                  
-                  docker stop coffeeapp-miahkykh-mysql || echo "MySQL container not running"
-                  docker rm coffeeapp-miahkykh-mysql || echo "MySQL container not found"
-                  docker pull mysql:latest
-                  docker run -d \
-                  --name coffeeapp-miahkykh-mysql \
-                  --net coffeestore-miahkykh \
-                  -e MYSQL_ROOT_PASSWORD=0000 \
-                  -e MYSQL_DATABASE=CoffeeAppMiahkykh \
-                  -p 3310:3306 \
-                  mysql:latest
-                  echo "MySQL container has been updated"
+          tags:
+            - ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest
+
+      - name: Restart MySQL container
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USERNAME }}
+          password: ${{ secrets.SSH_PASSWORD }}
+          script: |
+            if ! docker network ls | grep -q "coffeestore-miahkykh"; then
+              docker network create coffeestore-miahkykh
+            fi
+            echo "Restarting MySQL container"
+
+            docker stop coffeeapp-miahkykh-mysql || echo "MySQL container not running"
+            docker rm coffeeapp-miahkykh-mysql || echo "MySQL container not found"
+            docker pull mysql:latest || exit 1
+            docker run -d \
+              --name coffeeapp-miahkykh-mysql \
+              --net coffeestore-miahkykh \
+              -e MYSQL_ROOT_PASSWORD=0000 \
+              -e MYSQL_DATABASE=CoffeeAppMiahkykh \
+              -p 3310:3306 \
+              mysql:latest
+            echo "MySQL container has been updated"
 
       - name: Restart coffeeapp container
         uses: appleboy/ssh-action@v1.0.3
@@ -69,21 +69,17 @@ jobs:
           username: ${{ secrets.SSH_USERNAME }}
           password: ${{ secrets.SSH_PASSWORD }}
           script: |
-            if ! docker network ls | grep -q "coffeestore-miahkykh"; then  
-              docker network create coffeestore-miahkykh  
-            fi  
-            echo "Restarting coffeeapp container"  
-            
-            docker stop coffeeapp-miahkykh || echo "coffeeapp container not running"  
-            docker rm coffeeapp-miahkykh || echo "coffeeapp container not found"  
-            docker pull ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest  
-            docker run -d \  
-              --name coffeeapp-miahkykh \  
-              --net coffeestore-miahkykh \  
-              -p 8080:8080 \  
-              -e SPRING_DATASOURCE_URL=jdbc:mysql://coffeeapp-miahkykh-mysql:3306/CoffeeAppMiahkykh?createDatabaseIfNotExist=true \  
-              -e SPRING_DATASOURCE_USERNAME=root \  
-              -e SPRING_DATASOURCE_PASSWORD=0000 \  
-              ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest  
+            echo "Restarting coffeeapp container"
+
+            docker stop coffeeapp-miahkykh || echo "coffeeapp container not running"
+            docker rm coffeeapp-miahkykh || echo "coffeeapp container not found"
+            docker pull ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest || exit 1
+            docker run -d \
+              --name coffeeapp-miahkykh \
+              --net coffeestore-miahkykh \
+              -p 8080:8080 \
+              -e SPRING_DATASOURCE_URL=jdbc:mysql://coffeeapp-miahkykh-mysql:3306/CoffeeAppMiahkykh?createDatabaseIfNotExist=true \
+              -e SPRING_DATASOURCE_USERNAME=root \
+              -e SPRING_DATASOURCE_PASSWORD=0000 \
+              ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest
             echo "coffeeapp container has been updated"
-            exit
