Deploy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,14 +2,13 @@ name: Build and push coffeeapp image and restart containers
 
 on:
   push:
-    branches: [ "main" ]
-
+    branches: [ "master" ]
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4.2.2
+      - uses: actions/checkout@v4
 
       - name: Set up JDK 17
         uses: actions/setup-java@v3
@@ -22,6 +21,7 @@ jobs:
         run: |
           mvn clean package -DskipTests=true
 
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -29,63 +29,61 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3.9.0
+        uses: docker/setup-buildx-action@v3
 
       - name: Build and push coffeeapp image
-        uses: docker/build-push-action@v6.14.0
+        uses: docker/build-push-action@v5
         with:
           context: .
           file: ./Dockerfile
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest
+            - name: Restart MySQL container
+              uses: appleboy/ssh-action@v1.0.3
+              with:
+                host: ${{ secrets.SSH_HOST }}
+                username: ${{ secrets.SSH_USERNAME }}
+                password: ${{ secrets.SSH_PASSWORD }}
+                script: |
+                  if ! docker network ls | grep -q "coffeestore-miahkykh"; then
+                  docker network create coffeestore-miahkykh
+                  fi
+                  echo "Restarting MySQL container"
+                  
+                  docker stop coffeeapp-miahkykh-mysql || echo "MySQL container not running"
+                  docker rm coffeeapp-miahkykh-mysql || echo "MySQL container not found"
+                  docker pull mysql:latest
+                  docker run -d \
+                  --name coffeeapp-miahkykh-mysql \
+                  --net coffeestore-miahkykh \
+                  -e MYSQL_ROOT_PASSWORD=0000 \
+                  -e MYSQL_DATABASE=CoffeeAppMiahkykh \
+                  -p 3310:3306 \
+                  mysql:latest
+                  echo "MySQL container has been updated"
 
-      - name: SSH Restart MySQL container (Linux)
-        uses: appleboy/ssh-action@v1.2.1
+      - name: Restart coffeeapp container
+        uses: appleboy/ssh-action@v1.0.3
         with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USERNAME }}
           password: ${{ secrets.SSH_PASSWORD }}
-          port: 22
           script: |
-            if ! docker network ls | grep -q "coffeestore-miahkykh"; then
-              docker network create coffeestore-miahkykh
-            fi
-            echo "Restarting MySQL container"
+            if ! docker network ls | grep -q "coffeestore-miahkykh"; then  
+              docker network create coffeestore-miahkykh  
+            fi  
+            echo "Restarting coffeeapp container"  
             
-            docker stop coffeeapp-miahkykh-mysql || echo "MySQL container not running"
-            docker rm coffeeapp-miahkykh-mysql || echo "MySQL container not found"
-            docker pull mysql:latest
-            docker run -d \
-              --name coffeeapp-miahkykh-mysql \
-              --net coffeestore-miahkykh \
-              -e MYSQL_ROOT_PASSWORD=0000 \
-              -e MYSQL_DATABASE=CoffeeAppMiahkykh \
-              -p 3310:3306 \
-              mysql:latest
-            echo "MySQL container has been updated"
-
-      - name: SSH Restart coffeeapp container (Linux)
-        uses: appleboy/ssh-action@v1.2.1
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USERNAME }}
-          password: ${{ secrets.SSH_PASSWORD }}
-          port: 22
-          script: |
-            if ! docker network ls | grep -q "coffeestore-miahkykh"; then
-              docker network create coffeestore-miahkykh
-            fi
-            echo "Restarting coffeeapp container"
-            
-            docker stop coffeeapp-miahkykh || echo "coffeeapp container not running"
-            docker rm coffeeapp-miahkykh || echo "coffeeapp container not found"
-            docker pull ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest
-            docker run -d \
-              --name coffeeapp-miahkykh \
-              --net coffeestore-miahkykh \
-              -p 8080:8080 \
-              -e SPRING_DATASOURCE_URL=jdbc:mysql://coffeeapp-miahkykh-mysql:3306/CoffeeAppMiahkykh?createDatabaseIfNotExist=true \
-              -e SPRING_DATASOURCE_USERNAME=root \
-              -e SPRING_DATASOURCE_PASSWORD=0000 \
-              ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest
+            docker stop coffeeapp-miahkykh || echo "coffeeapp container not running"  
+            docker rm coffeeapp-miahkykh || echo "coffeeapp container not found"  
+            docker pull ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest  
+            docker run -d \  
+              --name coffeeapp-miahkykh \  
+              --net coffeestore-miahkykh \  
+              -p 8080:8080 \  
+              -e SPRING_DATASOURCE_URL=jdbc:mysql://coffeeapp-miahkykh-mysql:3306/CoffeeAppMiahkykh?createDatabaseIfNotExist=true \  
+              -e SPRING_DATASOURCE_USERNAME=root \  
+              -e SPRING_DATASOURCE_PASSWORD=0000 \  
+              ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest  
             echo "coffeeapp container has been updated"
+            exit
