Deploy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,7 +39,7 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/coffeeapp-miahkykh:latest
 
-      - name: SSH Deploy using Docker Compose
+      - name: SSH Restart MySQL container (Windows cmd)
         uses: appleboy/ssh-action@v1.2.1
         with:
           host: ${{ secrets.SSH_HOST }}
@@ -47,7 +47,28 @@ jobs:
           password: ${{ secrets.SSH_PASSWORD }}
           port: 22
           script: |
-            cd /path/to/your/application # IMPORTANT: Change this to the directory where you will place docker-compose.yml on the remote server
-            docker network ls | grep coffeestore-miahkykh || docker network create coffeestore-miahkykh
-            docker compose down || true
-            docker compose up -d
+            setlocal enabledelayedexpansion
+            docker network ls | findstr coffeestore-miahkykh || docker network create coffeestore-miahkykh
+            echo Restarting MySQL container
+            docker stop coffeeapp-miahkykh-mysql || echo "MySQL container not running"
+            docker rm coffeeapp-miahkykh-mysql || echo "MySQL container not found"
+            docker pull mysql:latest
+            docker run -d --name coffeeapp-miahkykh-mysql --net coffeestore-miahkykh -e MYSQL_ROOT_PASSWORD=0000 -e MYSQL_DATABASE=CoffeeAppMiahkykh -p 3310:3306 mysql:latest
+            echo MySQL container has been updated
+
+      - name: SSH Restart coffeeapp container (Windows cmd)
+        uses: appleboy/ssh-action@v1.2.1
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USERNAME }}
+          password: ${{ secrets.SSH_PASSWORD }}
+          port: 22
+          script: |
+            setlocal enabledelayedexpansion
+            docker network ls | findstr coffeestore-miahkykh || docker network create coffeestore-miahkykh
+            echo Restarting coffeeapp container
+            docker stop coffeeapp-miahkykh || echo "coffeeapp container not running"
+            docker rm coffeeapp-miahkykh || echo "coffeeapp container not found"
+            docker pull glyuchnoglaz21/coffeeapp-miahkykh:latest
+            docker run -d --name coffeeapp-miahkykh --net coffeestore-miahkykh -p 8080:8080 -e SPRING_DATASOURCE_URL=jdbc:mysql://coffeeapp-miahkykh-mysql:3306/CoffeeAppMiahkykh?createDatabaseIfNotExist=true -e SPRING_DATASOURCE_USERNAME=root -e SPRING_DATASOURCE_PASSWORD=0000 glyuchnoglaz21/coffeeapp-miahkykh:latest
+            echo coffeeapp container has been updated
